name: .NET Desktop CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest
    
    defaults:
      run:
        working-directory: ./marioprofejoyfe/juegosdam/JuegosDAM-final

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Compilar el proyecto
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    - name: Publicar la aplicación (Solo Release)
      if: matrix.configuration == 'Release'
      run: dotnet publish -c Release -o ./publish /p:UseAppHost=true

    - name: Compilar Instalador con Inno Setup
      if: matrix.configuration == 'Release'
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
      with:
        path: marioprofejoyfe/juegosdam/JuegosDAM-final/instalador.iss

    - name: Subir Artefacto (Instalador)
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: JuegosDAM-Setup
        # Ruta donde Inno Setup generó el .exe, basándose en la configuración del .iss
        path: ./marioprofejoyfe/juegosdam/JuegosDAM-final/Output/JuegosDAM_Setup.exe
