name: .NET Desktop CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [Release] # Quitamos Debug para que solo haga el instalador final

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Compilar el proyecto
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    - name: Publicar la aplicación
      run: dotnet publish -c Release -o ./publish /p:UseAppHost=true

    - name: Compilar Instalador con Inno Setup
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
      with:
        # Busca el archivo instalador.iss en la raíz del repositorio
        path: instalador.iss

    - name: Subir Artefacto (Instalador)
      uses: actions/upload-artifact@v4
      with:
        name: JuegosDAM-Setup
        # Busca el .exe generado en la carpeta Output
        path: Output/JuegosDAM_Setup.exe
